<?php

namespace ContainerENEiNJ9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PRBAMelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pRBAMel' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pRBAMel'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'houseRepositori' => ['privates', 'App\\Repository\\HouseRepository', 'getHouseRepositoryService', true],
        ], [
            'em' => '?',
            'houseRepositori' => 'App\\Repository\\HouseRepository',
        ]);
    }
}
