<?php

namespace ContainerENEiNJ9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_21OEILOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.21OEILO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.21OEILO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Api\\HouseController::getHouse' => ['privates', '.service_locator.slssIIr', 'get_ServiceLocator_SlssIIrService', true],
            'App\\Controller\\Api\\HouseController::getHouses' => ['privates', '.service_locator.slssIIr', 'get_ServiceLocator_SlssIIrService', true],
            'App\\Controller\\Api\\HouseController::postHouse' => ['privates', '.service_locator.IFW.IA7', 'get_ServiceLocator_IFW_IA7Service', true],
            'App\\Controller\\Api\\HouseController::setViewHandler' => ['privates', '.service_locator.srPvxhL', 'get_ServiceLocator_SrPvxhLService', true],
            'App\\Controller\\MainController::createHouse' => ['privates', '.service_locator.IFW.IA7', 'get_ServiceLocator_IFW_IA7Service', true],
            'App\\Controller\\MainController::getHouse' => ['privates', '.service_locator.pRBAMel', 'get_ServiceLocator_PRBAMelService', true],
            'App\\Controller\\MainController::list' => ['privates', '.service_locator.bZnbGX3', 'get_ServiceLocator_BZnbGX3Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Api\\HouseController:getHouse' => ['privates', '.service_locator.slssIIr', 'get_ServiceLocator_SlssIIrService', true],
            'App\\Controller\\Api\\HouseController:getHouses' => ['privates', '.service_locator.slssIIr', 'get_ServiceLocator_SlssIIrService', true],
            'App\\Controller\\Api\\HouseController:postHouse' => ['privates', '.service_locator.IFW.IA7', 'get_ServiceLocator_IFW_IA7Service', true],
            'App\\Controller\\Api\\HouseController:setViewHandler' => ['privates', '.service_locator.srPvxhL', 'get_ServiceLocator_SrPvxhLService', true],
            'App\\Controller\\MainController:createHouse' => ['privates', '.service_locator.IFW.IA7', 'get_ServiceLocator_IFW_IA7Service', true],
            'App\\Controller\\MainController:getHouse' => ['privates', '.service_locator.pRBAMel', 'get_ServiceLocator_PRBAMelService', true],
            'App\\Controller\\MainController:list' => ['privates', '.service_locator.bZnbGX3', 'get_ServiceLocator_BZnbGX3Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Api\\HouseController::getHouse' => '?',
            'App\\Controller\\Api\\HouseController::getHouses' => '?',
            'App\\Controller\\Api\\HouseController::postHouse' => '?',
            'App\\Controller\\Api\\HouseController::setViewHandler' => '?',
            'App\\Controller\\MainController::createHouse' => '?',
            'App\\Controller\\MainController::getHouse' => '?',
            'App\\Controller\\MainController::list' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Api\\HouseController:getHouse' => '?',
            'App\\Controller\\Api\\HouseController:getHouses' => '?',
            'App\\Controller\\Api\\HouseController:postHouse' => '?',
            'App\\Controller\\Api\\HouseController:setViewHandler' => '?',
            'App\\Controller\\MainController:createHouse' => '?',
            'App\\Controller\\MainController:getHouse' => '?',
            'App\\Controller\\MainController:list' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
