<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2xKW4Ex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2xKW4Ex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2xKW4Ex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2xKW4Ex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2xKW4Ex\App_KernelDevDebugContainer([
    'container.build_hash' => '2xKW4Ex',
    'container.build_id' => 'b526cd49',
    'container.build_time' => 1602228522,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2xKW4Ex');
